version: "3.8"

services:
  app:
    # image: my_python/app:1.0
    build: ./.docker/app
    # container_name: "my_python_app"
    ports:
      - "8080:80"
      - "8000:8000"
      - "8888:8888"
    stdin_open: true
    tty: true
    working_dir: "/workspace"
    volumes:
      - ./:/workspace
    depends_on:
      - mysql
      - mail

  mysql:
    # image: my_python/mysql:1.0
    build: ./.docker/mysql
    # container_name: 'my_python_db'
    expose:
      - "3306"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ="Asia/Tokyo"
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/mysql/_database:/var/lib/mysql∏
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    # container_name: phpmyadmin
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 8081:80

  mail:
    image: axllent/mailpit:v1.8
    container_name: mailpit
    ports:
      - 8025:8025
      - 1025:1025

  postgres:
    # image: my_python/postgresql:1.0
    build: ./.docker/postgres
    # container_name: 'my_python_db'
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sample
      - TZ="Asia/Tokyo"
    volumes:
      - ./.docker/postgres/init:/docker-entrypoint-initdb.d
      - ./.docker/postgres/_database:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:9
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./.docker/pgadmin4/servers.json:/pgadmin4/servers.json
      - ./.docker/pgadmin4/_pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
