version: "3.8"

services:
  app:
    image: my_python/app:1.0
    build: ./app
    container_name: "my_python_app"
    ports:
      - "8080:80"
      - "8000:8000"
    stdin_open: true
    tty: true
    working_dir: "/workspace"
    volumes:
      - ../:/workspace
    depends_on:
      - db

  db:
    image: my_python/mysql:1.0
    build: ./db
    container_name: "my_python_db"
    expose:
      - "3306"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ="Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/database:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 8081:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
